[project]
name = "riorai"
version = "2.1.0"
description = "Rior project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.18.2",
    "numpy>=2.3.3",
    "pydantic>=2.0.0",
    "pyyaml>=6.0.2",
    "ultralytics>=8.3.202",
]
