GLOBAL_CONFIGS:
  DEVICE: "cuda"

FLOOR_PLANE_DETECTION:
  MODEL:
    WEIGHTS: "data/models/floor_plane_model.pt"

  CONSTANTS:
    HASHMAP:
      Bath: 0
      Bathroom: 1
      Door: 2
      Shower Cabin: 3
      Sink: 4
      Toilet: 5
      Wash Machine: 6
    SCALE_CONSTANT: 0.1  # 0.75 ** 2
    DOOR_SIZE_IN_METERS: 0.8
    WALL_HEIGHT: 2.8
    
